version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    expose:
      - '5672'
    ports:
      - '5672:5672'
  slytherin:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bits_vanilla'
      MYSQL_USER: 'bits_vanilla'
      MYSQL_PASSWORD: 'rainbows'
      MYSQL_ROOT_PASSWORD: 'rainbows'
    expose:
      - '3306'
  db-import:
    build: db-import
    depends_on:
      - slytherin
    links:
      - slytherin
  player-api:
    image: player-api:dev
    depends_on:
      db-import:
        condition: service_completed_successfully
    links:
      - slytherin
      - rabbitmq
  warp-api:
    image: warp-api:dev
    depends_on:
      db-import:
        condition: service_completed_successfully
    links:
      - slytherin
      - rabbitmq
  chat-api:
    image: chat-api:dev
    depends_on:
      db-import:
        condition: service_completed_successfully
    links:
      - slytherin
      - rabbitmq
  server-api:
    image: server-api:dev
    depends_on:
      db-import:
        condition: service_completed_successfully
    links:
      - slytherin
      - rabbitmq
